# Generated by Django 5.2.1 on 2025-06-03 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_i18n",
                    models.JSONField(
                        help_text="Tag name in different languages, e.g., {'en': 'English Name', 'ro': 'Romanian Name'}",
                        verbose_name="name (i18n)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A short label for the tag, generally used in URLs.",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_i18n",
                    models.JSONField(
                        help_text="Problem title in different languages",
                        verbose_name="title (i18n)",
                    ),
                ),
                (
                    "statement_i18n",
                    models.JSONField(
                        help_text="Problem statement in different languages, can contain Markdown/HTML",
                        verbose_name="statement (i18n)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("PRIVATE", "Private"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "default_time_limit_ms",
                    models.IntegerField(
                        default=1000, verbose_name="default time limit (ms)"
                    ),
                ),
                (
                    "default_memory_limit_kb",
                    models.IntegerField(
                        default=262144, verbose_name="default memory limit (KB)"
                    ),
                ),
                (
                    "allowed_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of language identifiers allowed for this problem.",
                        verbose_name="allowed languages",
                    ),
                ),
                (
                    "custom_libraries_allowed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of custom library identifiers allowed.",
                        verbose_name="custom libraries allowed",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation date"
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_problems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_problems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="verifier",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="problems.tag", verbose_name="tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "problem",
                "verbose_name_plural": "problems",
                "ordering": ["-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="input data")),
                (
                    "expected_output_data",
                    models.TextField(verbose_name="expected output data"),
                ),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False,
                        help_text="Is this test case visible to users?",
                        verbose_name="is sample",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Points awarded for passing this test case.",
                        verbose_name="points",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of execution for the test case.",
                        verbose_name="order",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                        verbose_name="problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "test case",
                "verbose_name_plural": "test cases",
                "ordering": ["problem", "order"],
            },
        ),
    ]
