# Generated by Django 5.2.1 on 2025-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="comparison_mode",
            field=models.CharField(
                choices=[
                    ("EXACT", "Exact Match"),
                    ("STRIP_EXACT", "Exact Match (Ignore Leading/Trailing Whitespace)"),
                    (
                        "LINES_STRIP_EXACT",
                        "Line-by-Line Exact Match (Ignore Line Whitespace & Empty Lines)",
                    ),
                    ("FLOAT_PRECISE", "Floating Point (Precise up to Epsilon)"),
                ],
                default="LINES_STRIP_EXACT",
                help_text="How to compare user's output with expected output.",
                max_length=20,
                verbose_name="output comparison mode",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="float_comparison_epsilon",
            field=models.FloatField(
                blank=True,
                default=1e-06,
                help_text="Epsilon value for floating point comparisons (if mode is FLOAT_PRECISE).",
                null=True,
                verbose_name="float comparison epsilon",
            ),
        ),
    ]
