# Generated by Django 5.2.1 on 2025-06-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_problem_comparison_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="checker_code",
            field=models.TextField(
                blank=True,
                help_text="Source code for the custom checker program (if comparison_mode is CUSTOM_CHECKER).",
                null=True,
                verbose_name="checker code",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="checker_language",
            field=models.CharField(
                blank=True,
                help_text="Language of the custom checker (e.g., 'cpp17', 'python3').",
                max_length=50,
                null=True,
                verbose_name="checker language",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="comparison_mode",
            field=models.CharField(
                choices=[
                    ("EXACT", "Exact Match"),
                    ("STRIP_EXACT", "Exact Match (Ignore Leading/Trailing Whitespace)"),
                    (
                        "LINES_STRIP_EXACT",
                        "Line-by-Line Exact Match (Ignore Line Whitespace & Empty Lines)",
                    ),
                    ("FLOAT_PRECISE", "Floating Point (Precise up to Epsilon)"),
                    ("CUSTOM_CHECKER", "Use Custom Checker Program"),
                ],
                default="LINES_STRIP_EXACT",
                help_text="How to compare user's output with expected output.",
                max_length=20,
                verbose_name="output comparison mode",
            ),
        ),
    ]
