# Generated by Django 5.2.1 on 2025-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_problem_checker_code_problem_checker_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="verifier_feedback",
            field=models.TextField(
                blank=True,
                help_text="Feedback from the verifier if the problem status is set to Private or needs revision.",
                null=True,
                verbose_name="verifier feedback",
            ),
        ),
    ]
