# Generated by Django 5.2.1 on 2025-06-03 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Identifier for the programming language and version/compiler used.",
                        max_length=50,
                        verbose_name="language",
                    ),
                ),
                ("code", models.TextField(verbose_name="source code")),
                (
                    "submission_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submission time"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPILING", "Compiling"),
                            ("RUNNING", "Running"),
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("CE", "Compile Error"),
                            ("RE", "Runtime Error"),
                            ("IE", "Internal Error"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="verdict",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="execution time (ms)"
                    ),
                ),
                (
                    "memory_used_kb",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="memory used (KB)"
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="score"),
                ),
                (
                    "detailed_feedback",
                    models.TextField(blank=True, verbose_name="detailed feedback"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                        verbose_name="problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission",
                "verbose_name_plural": "submissions",
                "ordering": ["-submission_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "problem"],
                        name="submissions_user_id_1304bb_idx",
                    ),
                    models.Index(
                        fields=["problem", "submission_time"],
                        name="submissions_problem_aa2219_idx",
                    ),
                    models.Index(
                        fields=["user", "submission_time"],
                        name="submissions_user_id_af99a4_idx",
                    ),
                    models.Index(
                        fields=["verdict"], name="submissions_verdict_223995_idx"
                    ),
                ],
            },
        ),
    ]
