# Generated by Django 5.2.1 on 2025-06-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_problem_verifier_feedback"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPILING", "Compiling"),
                            ("RUNNING", "Running"),
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("CE", "Compile Error"),
                            ("RE", "Runtime Error"),
                            ("IE", "Internal Error"),
                        ],
                        help_text="Verdict for this specific test case.",
                        max_length=10,
                        verbose_name="verdict",
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="execution time (ms)"
                    ),
                ),
                (
                    "memory_used_kb",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="memory used (KB)"
                    ),
                ),
                (
                    "actual_output",
                    models.TextField(
                        blank=True, null=True, verbose_name="actual output"
                    ),
                ),
                (
                    "error_output",
                    models.TextField(
                        blank=True, null=True, verbose_name="error output"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="submissions.submission",
                        verbose_name="submission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_results",
                        to="problems.testcase",
                        verbose_name="test case",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission test result",
                "verbose_name_plural": "submission test results",
                "ordering": ["submission", "test_case__order"],
                "unique_together": {("submission", "test_case")},
            },
        ),
    ]
