# Generated by Django 2.2.12 on 2020-05-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0107_auto_20200507_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemgroup',
            name='description',
            field=models.CharField(max_length=100, verbose_name='problem group description'),
        ),
    ]
