# Generated by Django 2.2.12 on 2020-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0108_auto_20200507_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('es', 'Easy'), ('md', 'Medium'), ('hd', 'Hard')], default='es', max_length=7, verbose_name='Problem difficulty'),
        ),
    ]
