# Generated by Django 2.2.12 on 2020-05-13 01:06

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0111_auto_20200512_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemtype',
            options={'ordering': ['full_name'], 'verbose_name': 'problem tag', 'verbose_name_plural': 'problem tags'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'permissions': (('see_private_solution', 'See hidden solutions'),), 'verbose_name': 'official source', 'verbose_name_plural': 'official source'},
        ),
        migrations.AddField(
            model_name='problem',
            name='uploader',
            field=models.ForeignKey(help_text='This field register automatically who uploaded the problem to the platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_problems', to='judge.Profile', verbose_name='uploader'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='These users will be able to edit the problem, and be listed as authors.', related_name='authored_problems', to='judge.Profile', verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(db_index=True, help_text='The full, unique name of the problem, as shown in the problem list.', max_length=100, unique=True, verbose_name='problem name'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='partial',
            field=models.BooleanField(default=True, verbose_name='allows partial points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='types',
            field=models.ManyToManyField(help_text="A tag for the problem, as shown on the problem's page.", to='judge.ProblemType', verbose_name='problem tags'),
        ),
    ]
