# Generated by Django 2.2.12 on 2020-05-17 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0112_auto_20200513_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemgroup',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Select a parent group, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ProblemGroup', verbose_name='parent group'),
        ),
    ]
