# Generated by Django 2.2.12 on 2020-05-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0113_problemgroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemgroup',
            name='description',
        ),
    ]
