# Generated by Django 2.2.12 on 2020-05-18 14:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0114_remove_problemgroup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='problemgroup',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemgroup',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemgroup',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Select a parent group, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='judge.ProblemGroup', verbose_name='parent group'),
        ),
        migrations.AddField(
            model_name='problemgroup',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemgroup',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
