# Generated by Django 2.2.12 on 2020-05-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0115_auto_20200518_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Past contest name')),
                ('level', models.CharField(choices=[('lo', 'Local'), ('co', 'County'), ('ic', 'Inter-County'), ('nt', 'National'), ('ct', 'Continental'), ('it', 'International')], max_length=7, verbose_name='Contest level')),
                ('difficulty', models.CharField(choices=[('es', 'Easy'), ('md', 'Medium'), ('hd', 'Hard')], max_length=7, verbose_name='Contest difficulty')),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'past contest',
                'verbose_name_plural': 'past contests',
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('es', 'Easy'), ('md', 'Medium'), ('hd', 'Hard'), ('ct', 'Contest')], max_length=7, verbose_name='Problem difficulty'),
        ),
        migrations.CreateModel(
            name='ProblemGroupTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ro', 'Romanian')], max_length=7, verbose_name='language')),
                ('full_name', models.CharField(max_length=40, verbose_name='problem group name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='judge.ProblemGroup', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'problem group translation',
                'verbose_name_plural': 'problem group translations',
                'unique_together': {('group', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PastContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_contest_problems', to='judge.PastContest', verbose_name='related past contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_contests', to='judge.Problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'past contest problem',
                'verbose_name_plural': 'past contest problems',
                'unique_together': {('problem', 'past_contest')},
            },
        ),
    ]
