"""
Django settings for webcoder_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Import os for environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tra1bid*d3-t-+a$uu+1k&l+-aqxrp5u_ezlg5*oa%h$9cg45o"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "dj_rest_auth",
    "dj_rest_auth.registration",

    # Local apps
    "users.apps.UsersConfig",
    "problems.apps.ProblemsConfig",
    "submissions.apps.SubmissionsConfig",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

ROOT_URLCONF = "webcoder_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "webcoder_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "webcoder_db",  # Replace with your database name
        "USER": "webcoder_user",  # Replace with your PostgreSQL username
        "PASSWORD": "darkstarone",  # Replace with your PostgreSQL password
        "HOST": "localhost",  # Or your PostgreSQL host
        "PORT": "5432",  # Or your PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = [
    ('en', 'English'),
    ('ro', 'Romanian'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = "users.User"

# allauth settings
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'users.adapters.CustomSocialAccountAdapter'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGIN_ON_PASSWORD_CHANGE = True
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGIN_METHODS = ['username', 'email']
ACCOUNT_SIGNUP_FIELDS = {
    "username": {"required": True},
    "email"   : {"required": True},
    "password1": {"required": True},
}
DJ_REST_AUTH = {
    'SIGNUP_FIELDS': ACCOUNT_SIGNUP_FIELDS,
}
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'github': {
        'SCOPE': [
            'user',
            'repo',
            'read:org',
        ],
    }
}

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Django REST Framework settings
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Add other authentication classes if needed, e.g., SessionAuthentication for browsable API
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated', # Default to require authentication
    # ],
    # You can add other DRF settings here, like pagination, renderers, parsers etc.
}

# Simple JWT settings (optional, for customization)
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
from datetime import timedelta # Ensure timedelta is imported

# Reverting to all library defaults by setting SIMPLE_JWT to an empty dict
# or commenting it out entirely. Let's use an empty dict for now.
# SIMPLE_JWT = {} # Commenting this out to define specific keys below for debugging
# This will use the default 5-minute access token lifetime.

# Forcing SECRET_KEY usage explicitly for debugging token validation
SIMPLE_JWT = {
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': SECRET_KEY, # For symmetric algorithms, this should match SIGNING_KEY
    'ALGORITHM': 'HS256', # Explicitly state default
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5), # Default
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), # Default
    'LEEWAY': timedelta(seconds=0), # Default
    # Other settings can remain default or be added if needed
    "UPDATE_LAST_LOGIN": True, # Explicitly set this as it was in a previous attempt
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_USE_JWT = True
DJ_REST_AUTH = {
    "USE_JWT": True,
    'LOGIN_SERIALIZER': 'users.serializers.CustomLoginSerializer',
    'SIGNUP_FIELDS': ACCOUNT_SIGNUP_FIELDS,
}

# Celery Configuration Options
CELERY_BROKER_URL = 'filesystem://'
CELERY_BROKER_FOLDER_MAIN = os.path.join(BASE_DIR, '..', 'celery_broker')
CELERY_BROKER_FOLDER_PROCESSED = os.path.join(BASE_DIR, '..', 'celery_broker_processed')
CELERY_BROKER_FOLDER_SENT = os.path.join(BASE_DIR, '..', 'celery_broker_sent')
os.makedirs(CELERY_BROKER_FOLDER_MAIN, exist_ok=True)
os.makedirs(CELERY_BROKER_FOLDER_PROCESSED, exist_ok=True)
os.makedirs(CELERY_BROKER_FOLDER_SENT, exist_ok=True)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Custom Judge Settings
# Path on the host machine where Boost headers are located.
# This path will be mounted into the Docker container for C++ compilation
# when a problem specifies "boost_headers" in its custom_libraries_allowed.
# IMPORTANT: This path MUST exist on the judge server for this feature to work.
# For development, you might set this to a local path where you've downloaded Boost.
# It's recommended to use an environment variable for this in production.
# Example: "/opt/boost_1_82_0" or "C:/dev/boost_1_82_0" (adjust for your OS)
JUDGE_BOOST_HEADERS_PATH = os.environ.get('JUDGE_BOOST_HEADERS_PATH', "/opt/boost_headers") # Default to /opt/boost_headers if env var not set

# Path on the host machine where pre-approved Java JAR libraries are stored.
# This directory will be mounted into the Docker container for Java execution.
# Each JAR file in this directory will be added to the classpath.
# IMPORTANT: This path MUST exist on the judge server.
# Example: "/opt/java_libs"
JUDGE_JAVA_LIBS_DIR_HOST = os.environ.get('JUDGE_JAVA_LIBS_DIR_HOST', "/opt/java_libs")
